// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzpmnskbuepsfgoxjcpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56cG1uc2tidWVwc2Znb3hqY3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDgxNjQsImV4cCI6MjA3MDc4NDE2NH0.eTWJsdQwzeEkHy4YdURuA4hU860oCkuoLNtugsQtEyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});